### ISSUE TITLE
coll/restore-order should support an id selector fn like index-by

### ISSUE THREAD

**Issue by jeremyrsellars** [wilkerlucio/cljc-misc#3]
In a Pathom3 resolver, I wish to `restore-order` by a composite key like `{:mother 1, :father 2}`, using something like:

```clojure
(let [rows [{:mother 2, :father 1, :name "Cain", :id 3}]
      id-ks [:mother :father]]
  ...
  (coll/restore-order3 input
                       (fn id-selector [m] (select-keys m id-ks))
                       rows))
```

The `(defn restore-order` code at https://github.com/wilkerlucio/cljc-misc/blob/9fb7574a3acfcc64533eca1c83cf808ee315f8ac/src/main/com/wsscode/misc/coll.cljc#L331-L337 looks up a key in the map, but could just-as easily look-up by fn instead of key, like `index-by` does, and which could like like:

```
                  (or (get index (key input))
                      (default-fn input))))
```

I suppose this could be implemented by a change to `restore-order` and thus also `restore-order2`.  Edit: It would not be a breaking change because `index-by` already assumes the key `f` is an `ifn` when the key is called at https://github.com/wilkerlucio/cljc-misc/blob/9fb7574a3acfcc64533eca1c83cf808ee315f8ac/src/main/com/wsscode/misc/coll.cljc#L60.

If this sounds like a worthwhile addition, I would be glad to create a PR at your direction.

**Comment by wilkerlucio** [comment]
Hi @jeremyrsellars, thanks for reaching out. I like the idea, can you please send a PR for it?
